#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# DNS-based domain whitelist firewall.
#
# Configures dnsmasq as a local resolver that only resolves whitelisted
# domains, then applies iptables rules to force all DNS through it.
#
# Reads:  /opt/config/allowed-domains.txt        (bind-mounted dir or baked-in)
#         /opt/config/allowed-domains.local.txt  (optional, gitignored)
# Env:    EXTRA_ALLOWED_DOMAINS — comma-separated additional domains
#
# A background watcher polls the domains file every 10s and hot-reloads
# dnsmasq when changes are detected (no container restart needed).
#
# Runs as root from entrypoint.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

ALLOWED_DOMAINS_FILE="/opt/config/allowed-domains.txt"
ALLOWED_DOMAINS_LOCAL="/opt/config/allowed-domains.local.txt"
DNSMASQ_CONF="/etc/dnsmasq.d/whitelist.conf"
UPSTREAM_DNS_FILE="/run/dns-firewall-upstream"

if [ ! -f "$ALLOWED_DOMAINS_FILE" ]; then
  echo "[firewall] WARN: $ALLOWED_DOMAINS_FILE not found — skipping DNS firewall"
  exit 0
fi

# ── Capture upstream DNS before we overwrite resolv.conf ─────────────────────
UPSTREAM_DNS=$(grep -m1 '^nameserver' /etc/resolv.conf | awk '{print $2}')
UPSTREAM_DNS="${UPSTREAM_DNS:-8.8.8.8}"
echo "$UPSTREAM_DNS" > "$UPSTREAM_DNS_FILE"
echo "[firewall] Upstream DNS: $UPSTREAM_DNS"

# ── Generate dnsmasq whitelist config from domains file + env var ────────────
generate_config() {
  local upstream
  upstream=$(cat "$UPSTREAM_DNS_FILE")

  {
    echo "# Auto-generated domain whitelist"

    # Domains from file(s)
    for f in "$ALLOWED_DOMAINS_FILE" "$ALLOWED_DOMAINS_LOCAL"; do
      [ -f "$f" ] || continue
      while IFS= read -r line; do
        domain=$(echo "$line" | sed 's/#.*//' | tr -d '[:space:]')
        [ -z "$domain" ] && continue
        echo "server=/${domain}/${upstream}"
      done < "$f"
    done

    # Extra domains from environment variable (comma-separated)
    if [ -n "${EXTRA_ALLOWED_DOMAINS:-}" ]; then
      echo "# Extra domains from EXTRA_ALLOWED_DOMAINS"
      IFS=',' read -ra extras <<< "$EXTRA_ALLOWED_DOMAINS"
      for domain in "${extras[@]}"; do
        domain=$(echo "$domain" | tr -d '[:space:]')
        [ -z "$domain" ] && continue
        echo "server=/${domain}/${upstream}"
      done
    fi
  } > "$DNSMASQ_CONF"

  grep -c '^server=' "$DNSMASQ_CONF"
}

# ── Write base dnsmasq configuration ────────────────────────────────────────
mkdir -p /etc/dnsmasq.d

cat > /etc/dnsmasq.conf <<'CONF'
# Auto-generated by setup-dns-firewall.sh — do not edit
no-resolv
no-poll
listen-address=127.0.0.1
bind-interfaces
cache-size=1000
conf-dir=/etc/dnsmasq.d/,*.conf
CONF

# ── Initial config generation + dnsmasq start ───────────────────────────────
DOMAIN_COUNT=$(generate_config)
dnsmasq --test 2>&1 | sed 's/^/[firewall] /'
dnsmasq
echo "[firewall] dnsmasq started"

# ── Point resolver at our local dnsmasq ──────────────────────────────────────
echo "nameserver 127.0.0.1" > /etc/resolv.conf
echo "[firewall] resolv.conf updated"

# ── iptables: force DNS through local dnsmasq ────────────────────────────────
# 1. Allow all loopback traffic (dnsmasq <-> Docker DNS, localhost)
iptables -A OUTPUT -o lo -j ACCEPT

# 2. Allow established / related connections
iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

# 3. Block DNS to any external server (force through our dnsmasq)
iptables -A OUTPUT -p udp --dport 53 -j DROP
iptables -A OUTPUT -p tcp --dport 53 -j DROP

# 4. Allow all other outbound traffic (gated by DNS resolution)
iptables -A OUTPUT -j ACCEPT

echo "[firewall] iptables rules applied"
echo "[firewall] Domain whitelist active ($DOMAIN_COUNT domains)"

# ── Background watcher: hot-reload on file change ───────────────────────────
# Polls mtime every 10s. inotify is unreliable on Docker bind mounts.
(
  LAST_MTIME=$(stat -c '%Y' "$ALLOWED_DOMAINS_FILE" 2>/dev/null || echo 0)
  LAST_MTIME_LOCAL=$(stat -c '%Y' "$ALLOWED_DOMAINS_LOCAL" 2>/dev/null || echo 0)
  while true; do
    sleep 10
    CUR_MTIME=$(stat -c '%Y' "$ALLOWED_DOMAINS_FILE" 2>/dev/null || echo 0)
    CUR_MTIME_LOCAL=$(stat -c '%Y' "$ALLOWED_DOMAINS_LOCAL" 2>/dev/null || echo 0)
    if [ "$CUR_MTIME" != "$LAST_MTIME" ] || [ "$CUR_MTIME_LOCAL" != "$LAST_MTIME_LOCAL" ]; then
      NEW_COUNT=$(generate_config)
      # Restart dnsmasq to pick up new config
      kill "$(cat /run/dnsmasq.pid 2>/dev/null)" 2>/dev/null || true
      sleep 0.5
      dnsmasq
      LAST_MTIME="$CUR_MTIME"
      LAST_MTIME_LOCAL="$CUR_MTIME_LOCAL"
      echo "[firewall] Reloaded — $NEW_COUNT domains (file changed)"
    fi
  done
) &
